# ==========================================
# SERVER CONFIGURATION
# ==========================================
server.port=${PORT:8080}


# ==========================================
# MONGODB CONFIGURATION
# ==========================================
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}


# ==========================================
# FILE STORAGE CONFIGURATION
# ==========================================
securevideo.storage.path=./storage
securevideo.storage.chunks=./storage/chunks
securevideo.storage.videos=./storage/videos


# ==========================================
# JWT CONFIGURATION
# ==========================================
securevideo.jwt.secret=${SECUREVIDEO_JWT_SECRET}
securevideo.jwt.expiration=86400000


# ==========================================
# SHARE LINK CONFIGURATION
# ==========================================
securevideo.share.expiration-hours=24

# Local Development
# securevideo.share.base-url=http://localhost:5173/share

# Production (Render)
securevideo.share.base-url=https://secure-vedio-project.vercel.app/share


# ==========================================
# FILE UPLOAD LIMITS
# ==========================================
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB


# ==========================================
# RESEND CONFIGURATION
# ==========================================
resend.api.key=${RESEND_API_KEY}